name: GitRepo Test and Deploy
on: [push]
jobs:
  install_and_build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # report machine parameters
      - run: yarn cypress info
      - run: node -p 'os.cpus()'

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build  

      - name: Save .next folder
        uses: actions/upload-artifact@v3
        with:
          name: .next
          if-no-files-found: error
          path: .next
        
      - name: Save out folder
        uses: actions/upload-artifact@v3
        with:
          name: out
          if-no-files-found: error
          path: out


  cypress-testing:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: install_and_build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: .next
          path: .next

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          command-prefix: 'yarn'
  
  deploy:
    runs-on: ubuntu-latest
    needs: cypress-testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out